import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" type="image/png" sizes="32x32" href="/favicon.png" />
				<title>Space tourism</title>
			</Head>
			<nav role="navigation"></nav>
			<main role="main">
				<h1></h1>
			</main>

			<footer role="contentinfo"></footer>
		</div>
	);
}
